name: CI Build and Test
# Žrtva koristi pull_request_target da bi imala prava za ostavljanje komentara
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout PR koda
        uses: actions/checkout@v3
        with:
          # FATALNA GREŠKA: Admin eksplicitno skida kod od nepoznatog napadača
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: 2. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: 3. Pokreni testove
        # Ovdje će server žrtve izvršiti 'npm test' iz napadačevog fajla!
        run: npm install && npm test
        
      - name: 4. Ostavljanje komentara
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hvala na doprinosu! Tvoji testovi su uspješno prošli.'
            })
