name: Issue Triage Bot
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto_reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # <--- OVO DODAJ! Normalni ljudi ovo uvijek imaju.
      
      - name: Snimi sadrzaj
        run: |
          echo "Sadrzaj issue-a je:"
          echo "${{ github.event.issue.body }}" > issue_log.txt
          echo "Zavrseno snimanje!"
